site_name: Kho Từ Vựng Tiếng Anh

theme:
  name: material
  palette:
    primary: white
    accent: blue
  font:
    text: Helvetica Neue, Helvetica, Arial, sans-serif
  features:
    #  - navigation.instant
      - navigation.footer
    #  - search.suggest     # Bật tính năng tự động gợi ý từ khóa khi đang gõ
    #  - search.highlight   # Bôi vàng từ khóa trong bài học
  
nav:
  - Trang chủ: index.md

  #============================
  # MEMRISE: KHÓA HỌC ANH - MỸ
  #============================
  - Memrise:
    - 🍔 Ăn uống & Nhà hàng:
      - Chủ đề Ăn uống:
        - Tổng hợp chủ đề Ăn uống: Nhà hàng & Ăn uống/Đồ ăn/Tổng hợp ăn uống.md
        - Bài 1. Đồ ăn: Nhà hàng & Ăn uống/Đồ ăn/Đồ ăn.md
        - Bài 2. Nhiều đồ ăn hơn: Nhà hàng & Ăn uống/Đồ ăn/Nhiều đồ ăn hơn.md
      - Chủ đề Nhà hàng:
        - Tổng hợp chủ đề Nhà hàng: Nhà hàng & Ăn uống/Ở nhà hàng/Ở nhà hàng.md
        - Bài 1. Ở nhà hàng 1: Nhà hàng & Ăn uống/Ở nhà hàng/Ở nhà hàng 1.md
        - Bài 2. Ở nhà hàng 2: Nhà hàng & Ăn uống/Ở nhà hàng/Ở nhà hàng 2.md
        - Bài 3. Ở nhà hàng 3: Nhà hàng & Ăn uống/Ở nhà hàng/Ở nhà hàng 3.md
        - Bài 4. Ở nhà hàng 4: Nhà hàng & Ăn uống/Ở nhà hàng/Ở nhà hàng 4.md
        - Bài 5. Ở nhà hàng 5: Nhà hàng & Ăn uống/Ở nhà hàng/Ở nhà hàng 5.md
        - Bài 6. Ở nhà hàng 6: Nhà hàng & Ăn uống/Ở nhà hàng/Ở nhà hàng 6.md

    - 🛒 Mua sắm & Cửa hàng:
      - Chủ đề Nhịp sống đô thị:
        - Tổng hợp chủ đề Nhịp sống đô thị: Mua sắm & Cửa hàng/Các cửa hàng trong khu phố/Các cửa hàng trong khu phố.md
        - Bài 1. Các cửa hàng trong khu phố 1 : Mua sắm & Cửa hàng/Các cửa hàng trong khu phố/015. Các cửa hàng trong khu phố 1 (17 từ).md
        - Bài 2. Các cửa hàng trong khu phố 2: Mua sắm & Cửa hàng/Các cửa hàng trong khu phố/032. Các cửa hàng trong khu phố 2 (27 từ).md
        - Bài 3. Các cửa hàng trong khu phố 3: Mua sắm & Cửa hàng/Các cửa hàng trong khu phố/Các cửa hàng trong khu phố 3.md
        - Bài 4. Các cửa hàng trong khu phố 4: Mua sắm & Cửa hàng/Các cửa hàng trong khu phố/Các cửa hàng trong khu phố 4.md
        - Bài 5. Các cửa hàng trong khu phố 5: Mua sắm & Cửa hàng/Các cửa hàng trong khu phố/Các cửa hàng trong khu phố 5.md
      - Chủ đề Mua sắm:
        - Tổng hợp chủ đề Mua sắm: Mua sắm & Cửa hàng/Mua sắm/Mua sắm.md
        - Bài 1. Mua sắm 1: Mua sắm & Cửa hàng/Mua sắm/Mua sắm 1.md
        - Bài 2. Mua sắm 2: Mua sắm & Cửa hàng/Mua sắm/Mua sắm 2.md
        - Bài 3. Mua sắm 3: Mua sắm & Cửa hàng/Mua sắm/Mua sắm 3.md
        - Bài 4. Mua sắm 4: Mua sắm & Cửa hàng/Mua sắm/Mua sắm 4.md
        - Bài 5. Mua sắm 5: Mua sắm & Cửa hàng/Mua sắm/Mua sắm 5.md

    - 👫 Con người & Các mối quan hệ:
      - Gia đình & Quan hệ cơ bản:
        - Tổng hơp chủ đề Gia đình & Quan hệ cơ bản: Con người & Các mối quan hệ/Gia đình & Quan hệ cơ bản/Gia đình & Quan hệ cơ bản.md
        - Bài 1. Gia đình: Con người & Các mối quan hệ/Gia đình & Quan hệ cơ bản/Gia đình.md
        - Bài 2. Bạn bè: Con người & Các mối quan hệ/Gia đình & Quan hệ cơ bản/Bạn bè.md
        - Bài 3. Giới thiệu mọi người: Con người & Các mối quan hệ/Gia đình & Quan hệ cơ bản/Giới thiệu mọi người.md
      #- Tình yêu & Hẹn hò:
      #  - Bài 1. Đang yêu:
      #  - Bài 2. Tình yêu và nỗi đau:
      #- Tính cách & Hình mẫu:
      #  - Bài 1. Mô tả người:
      #  - Bài 2. Người bạn đời lý tưởng của tôi:
      #- Cảm xúc & Ứng xử:
      #  - Bài 1. Bạn cảm thấy thế nào?:
      #  - Bài 2. Mô tả người ta:
      #  - Bài 3. Mối quan hệ giữa con người:


  #=======================================
  # DAILYDICTATION: LUYÊN NGHE TIẾNG ANH
  #=======================================
  - DailyDictation:
    - 💬 Conversations:
      - 001-002 At Home: DailyDictation/Conversations/001-002-At home.md
      - 003-My Favorite Photographs: DailyDictation/Conversations/003-My Favorite Photographs.md
      - 004-005-Location: DailyDictation/Conversations/004-005-Location.md
      - 006-007-Color: DailyDictation/Conversations/006-007-Color.md
      - 008-No questions: DailyDictation/Conversations/008-No questions.md
      - 009-Short Answer: DailyDictation/Conversations/009-Short Answer.md
      - 010-Telephone call: DailyDictation/Conversations/010-Telephone call.md


extra_css:
  - stylesheets/custom.css

extra_javascript:
  - javascripts/custom.js
  
# Thêm khối plugins này vào (nếu chưa có)
plugins:
  - search
  - macros
  - glightbox
