site_name: Kho Từ Vựng Memrise

theme:
  name: material
  palette:
    primary: white
    accent: blue
  font:
    text: Helvetica Neue, Helvetica, Arial, sans-serif
  features:
      - navigation.instant
      - navigation.footer
  
nav:
  - Trang chủ: index.md
  - Đồ ăn:
    - Tổng hợp từ vựng: Đồ ăn/Tổng hợp đồ ăn.md
    - Đồ ăn: Đồ ăn/Đồ ăn.md
    - Nhiều đồ ăn hơn: Đồ ăn/Nhiều đồ ăn hơn.md
  - Ở nhà hàng:
    - Tổng hợp từ vựng: Ở nhà hàng/Ở nhà hàng.md
    - Ở nhà hàng 1: Ở nhà hàng/Ở nhà hàng 1.md
  - Các cửa hàng trong khu phố:
    - Tổng hợp từ vựng: Các cửa hàng trong khu phố/Các cửa hàng trong khu phố.md
    - Các cửa hàng trong khu phố 1 : Các cửa hàng trong khu phố/015. Các cửa hàng trong khu phố 1 (17 từ).md
    - Các cửa hàng trong khu phố 2: Các cửa hàng trong khu phố/032. Các cửa hàng trong khu phố 2 (27 từ).md
    - Các cửa hàng trong khu phố 3: Các cửa hàng trong khu phố/038. Các cửa hàng trong khu phố 3 (16 từ).md
    - Các cửa hàng trong khu phố 4: Các cửa hàng trong khu phố/040. Các cửa hàng trong khu phố 4 (18 từ).md
    - Các cửa hàng trong khu phố 5: Các cửa hàng trong khu phố/041. Các cửa hàng trong khu phố 5 (14 từ).md

extra_css:
  - stylesheets/custom.css
  
# Thêm khối plugins này vào (nếu chưa có)
plugins:
  - search
  - macros
  - glightbox

# Thêm file JS vào cùng chỗ với extra_css
extra_javascript:
  - javascripts/custom.js
